Repository dhirajwork/OSSE-ASSIGNMENT, pull requests merged in 2021-12, with the labels that each got.

#11 feature(ci): github action pr check builds
  .github/workflows/maven.yml
Labels: New Feature

#15 Added base structure of SpringBoot project
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/osse/hotelreservation/assignment/AssignmentApplication.java
  src/main/resources/application.properties
  src/test/java/com/osse/hotelreservation/assignment/AssignmentApplicationTests.java
Labels: Review ready

#16 implemented the end-point for creating new reservation
  pom.xml
  src/main/java/com/osse/hotelreservation/assignment/controller/HotelReservationController.java
  src/main/java/com/osse/hotelreservation/assignment/entity/Reservation.java
  src/main/java/com/osse/hotelreservation/assignment/temp/CurrentReservation.java
  src/main/resources/application.properties
Labels: Review ready

#17 implemented the end-point to get all reservations of logged-in user
  src/main/java/com/osse/hotelreservation/assignment/controller/HotelReservationController.java
  src/main/java/com/osse/hotelreservation/assignment/entity/Role.java
  src/main/java/com/osse/hotelreservation/assignment/entity/User.java
  src/main/java/com/osse/hotelreservation/assignment/repository/ReservationRep.java
  src/main/java/com/osse/hotelreservation/assignment/services/ReservationService.java
  src/main/java/com/osse/hotelreservation/assignment/services/ReservationServiceImpl.java
  src/main/java/com/osse/hotelreservation/assignment/services/UserService.java
  src/main/java/com/osse/hotelreservation/assignment/temp/CurrentUser.java
  src/main/java/com/osse/hotelreservation/assignment/validation/EmailValidator.java
  src/main/java/com/osse/hotelreservation/assignment/validation/FieldMatch.java
  src/main/java/com/osse/hotelreservation/assignment/validation/FieldMatchValidator.java
  src/main/java/com/osse/hotelreservation/assignment/validation/ValidEmail.java
  src/main/resources/templates/reservation-page.html
  src/main/resources/templates/your-reservations.html
Labels: Review ready

#18 implemented the end-point to delete a reservation by ID
  src/main/java/com/osse/hotelreservation/assignment/controller/HotelReservationController.java
  src/main/java/com/osse/hotelreservation/assignment/services/ReservationService.java
  src/main/java/com/osse/hotelreservation/assignment/services/ReservationServiceImpl.java
Labels: Review ready

#19 added new home api & dao
  src/main/java/com/osse/hotelreservation/assignment/controller/HotelReservationController.java
  src/main/java/com/osse/hotelreservation/assignment/dao/ReservationDao.java
  src/main/java/com/osse/hotelreservation/assignment/dao/ReservationDaoImpl.java
Labels: New Feature

#23 feature(login-page): added login html page
  src/main/resources/templates/home-page.html
  src/main/resources/templates/login.html
Labels: New Feature

#34 Document: Update readme file with meaningful information about the project
  README.md
Labels: documentation

#38 update ReadMe file
  README.md
Labels: Review ready

#39 update ReadMe file
  README.md
Labels: Review ready
